[유동헌] feat: create comment and recomment inquiry function
wanted-InfinityLoop/aimmo-InfinityLoop-2 pull request #15
Opened 2021-12-14 15:46 UTC by dhhyy

- 댓글, 대댓글 조회 기능 구현
- 조회 기능 pagination 구현

2021-12-14 16:50 UTC, Odreystella requested changes

2021-12-14 16:50 UTC, Odreystella commented on postings/views.py
>          except KeyError:
CommentSerializer에서 지정한 fields들만 request.body로 받다 보니까 키가 잘못들어오는 일은 없는것 같아요! 다만 content에 값이 없을 경우는 192, 193 로직에서 에러 핸들링이 되니 해당 예외절이 필요한가 싶은데 어떻게 생각하시나요?!

2021-12-14 16:50 UTC, Odreystella commented on postings/views.py
>              if not (content and posting_id):
posting_id가 안들어오는 경우도 if 로직에 포함되어야 하나요??

2021-12-14 16:50 UTC, Odreystella commented on postings/views.py
> +        type = openapi.TYPE_STRING
257번 줄이랑 같이 type을 string로 해놓으면 스웨거 문서상 해당 쿼리 파라미터가 string라고 표시되어져서 이부분 INTEGER로 바꾸는게 좋을지 한번 고민해봐요!

2021-12-14 16:50 UTC, Odreystella commented on postings/views.py
> +
공백은 없는게 좋을것 같아요!

2021-12-14 16:50 UTC, Odreystella commented on postings/views.py
> +            print(type(limit))
print문 삭제해야 할 것 같습니다ㅎㅎㅎ

2021-12-14 16:50 UTC, Odreystella commented on postings/views.py
> +#     ...
ㅎㅎㅎ이 부분도 지워야 할 것 같습니다! 아, 위쪽에 스웨거 데코레이터 붙인 부분에 346, 348번 줄처럼 drf-yasg 장점인 responses도 한번 추가해보면 좋을 것 같습니다!

2021-12-15 06:07 UTC, dhhyy commented on postings/views.py
>          except KeyError:
네, 문서화를 통해 key 값이 명시 되어 있으니 예외절은 없어도 될 거 같습니다. 직접 실행해보니 key에 오타가 있을 때도 잡아주네요. 삭제해도 될 것 같습니다. 
그리고 새로운 댓글 및 대댓글이 '생성'이 되는 거니까 status_code도 200에서 201로 바꾸는 건 어떨까요? 
메세지도 현재는 POST RECOMMENT라고 되어 있는데, 좀 명확하게 CREATE_COMMENT,  CREATE_RECOMMENT 이렇게 바꾸는 건 어떨까요?

2021-12-15 06:12 UTC, dhhyy commented on postings/views.py
>          except KeyError:
그리고 recomment 부분을 매번 body에서 바꿔야 하는 부분도 custom해서 문서에 표현하는 걸로 고쳐야 될 거 같습니다!

2021-12-15 06:20 UTC, dhhyy commented on postings/views.py
>              if not (content and posting_id):
저희가 포스트맨으로 작업을 할 땐 이렇게 포함을 시켜주지 않았었나요? 지금 swagger 문서에서 확인을 해보니 posting_id가 아예 없으면 붉은색으로 처리가 되면서 API 호출 자체가 안되긴 합니다. 수정이 필요한지는.. 잘 모르겠습니다. 논의를 통해 결정하면 좋겠습니다!

2021-12-15 06:20 UTC, dhhyy commented on postings/views.py
> +        type = openapi.TYPE_STRING
넵!!

2021-12-15 06:20 UTC, dhhyy commented on postings/views.py
> +
네 이 부분은 바로 수정했습니다!

2021-12-15 06:21 UTC, dhhyy commented on postings/views.py
> +            print(type(limit))
넵 수정했습니다!

2021-12-15 06:22 UTC, dhhyy commented on postings/views.py
> +#     ...
넵 그렇게 하시죠! 일단 주석 부분은 삭제했습니다!

2021-12-15 14:11 UTC, Odreystella approved these changes

2021-12-15 14:16 UTC, merged